### ISSUE TITLE
Ethereum Wallets

### ISSUE THREAD

**Issue by awoox2** [awoox2/personal-crypto#7]
Add Ethereum and ERC-20 tracking

**Comment by BruceLegrand** [comment]
Hello, can somebody help me? I am a bit of a newby but i have some ethereum, and i had it on my old computer. I have got version 0.9.3 ethereum wallet.. I think this is one is old? And its keep saying Looking  for peers... but nothing happens..

**Comment by awoox2** [comment]
I'm a bit confused about what you are asking. This is just a utility to check the values of assets in a ETH wallet. This does not directly connect to the Ethereum Network. You shouldn't see anything to do with peers. Perhaps you are looking for the official Ethereum repo?

**Comment by awoox2** [comment]
Added in 0.1.2

**Comment by BruceLegrand** [comment]
Good morning Adam,

I have got the application Ethereum Wallet, but it doesn't work anymore...
i have got my crypto address and recovery code but i cant login now...

Best regards Brice


Op za 20 feb. 2021 om 20:26 schreef Adam Woo <notifications@github.com>:
